# Stocks Dataset Analysis

In [31]:
import numpy as np
import pandas as pd
import statistics as st

In [76]:
np.set_printoptions(suppress=True, precision=2)

## Overview of the Dataset

In [77]:
data=pd.read_excel('/Users/kamyasindhu/Downloads/synthetic_stock_market_dataset.xlsx')

In [78]:
data

,Date,Open,High,Low,Close,Volume
0,2024-01-01,150.84,151.53,148.28,149.01,959791
1,2024-01-02,150.07,157.26,148.92,152.44,349957
2,2024-01-03,150.00,152.24,144.98,149.05,4671300
3,2024-01-04,148.57,152.44,145.98,151.60,1439319
4,2024-01-05,152.79,155.84,151.12,155.64,2923559
...,...,...,...,...,...,...
495,2025-05-10,174.74,177.59,172.45,173.05,3231518
496,2025-05-11,174.21,178.54,170.57,171.67,3318792
497,2025-05-12,171.21,175.36,166.68,174.66,1553198
498,2025-05-13,174.99,179.16,173.44,175.24,3883270


In [79]:
arr=np.array(data[['Open','High','Low','Close','Volume']])

In [80]:
arr

array([[    150.84,     151.53,     148.28,     149.01,  959791.  ],
       [    150.07,     157.26,     148.92,     152.44,  349957.  ],
       [    150.  ,     152.24,     144.98,     149.05, 4671300.  ],
       ...,
       [    171.21,     175.36,     166.68,     174.66, 1553198.  ],
       [    174.99,     179.16,     173.44,     175.24, 3883270.  ],
       [    175.96,     182.95,     168.32,     175.41, 1736856.  ]],
      shape=(500, 5))

In [81]:
arr.shape

(500, 5)

In [82]:
arr.size

2500

In [83]:
arr.ndim

2

In [84]:
arr.dtype

dtype('float64')

In [85]:
print(type(arr))

<class 'numpy.ndarray'>


In [86]:
open_price=arr[:,0]
close_price=arr[:,3]
high=arr[:,1]
low=arr[:,2]
volume=arr[:,4]

In [87]:
print(open_price)
print()
print(close_price)
print()
print(high)
print()
print(low)
print()
print(volume)

[150.84 150.07 150.   148.57 152.79 153.25 154.15 157.31 159.56 163.14
 162.24 161.54 166.11 166.11 162.19 167.57 163.29 163.71 167.16 163.96
 164.92 159.22 159.99 163.9  162.76 163.37 158.83 158.54 156.24 155.97
 157.84 163.57 163.01 160.3  161.97 162.14 164.25 162.27 153.22 146.22
 146.9  144.17 149.7  148.09 147.03 148.15 143.83 142.67 144.26 146.59
 146.88 150.27 145.11 139.66 140.18 136.41 138.47 135.09 138.11 133.27
 128.74 125.78 126.86 128.74 129.13 127.51 131.7  129.61 133.36 130.98
 132.78 129.62 127.35 127.31 132.79 139.26 133.33 134.33 134.96 138.47
 139.08 140.61 142.26 143.71 138.66 135.85 139.6  135.89 132.69 131.05
 139.   142.85 141.82 138.46 139.19 139.85 136.12 142.67 138.17 141.34
 137.08 140.07 143.76 137.06 137.74 131.97 130.62 125.99 125.58 123.74
 125.45 125.71 129.86 127.87 131.85 129.19 129.21 131.65 129.77 130.56
 125.88 125.17 121.94 121.46 123.14 120.62 124.28 123.18 124.35 129.39
 130.43 126.77 127.2  125.84 121.93 118.64 109.94 115.46 110.15 113.4
 110.6 

## Statistical Analysis

In [88]:
print('mean',np.mean(close_price))
print('median',np.median(close_price))
print('min',np.min(close_price))
print('max',np.max(close_price))
print('std',np.std(close_price))
print('var',np.var(close_price))
print('mode',st.mode(close_price))

mean 169.04342
median 171.735
min 108.45
max 222.6
std 28.731073709550085
var 825.4745965036
mode 160.71


In [89]:
print('mean',np.mean(open_price))
print('median',np.median(open_price))
print('min',np.min(open_price))
print('max',np.max(open_price))
print('std',np.std(open_price))
print('var',np.var(open_price))
print('mode',st.mode(open_price))

mean 169.0096
median 171.42000000000002
min 106.53
max 224.19
std 28.671046730804928
var 822.02892064
mode 175.71


In [90]:
print(np.percentile(close_price,25),
np.percentile(open_price,75),
np.percentile(open_price,90),
np.percentile(open_price,50))

142.8825 191.385 206.602 171.42000000000002


In [91]:
arr[np.argmax(close_price)]

array([   217.24,    224.03,    216.18,    222.6 , 506968.  ])

In [92]:
arr[np.argmin(close_price)]

array([   106.53,    109.19,    103.91,    108.45, 697099.  ])

In [93]:
price_range=high-low

In [94]:
price_range

array([ 3.25,  8.34,  7.26,  6.46,  4.72,  6.54, 10.49,  7.91,  6.62,
       13.91,  6.52,  6.67,  5.08,  9.19,  4.51,  8.28,  7.64,  5.64,
       13.13,  4.65, 14.74,  7.03,  2.21, 10.52,  6.3 , 10.82,  4.56,
        7.07, 12.33,  6.2 , 11.83,  9.16,  1.64,  6.75,  3.32, 13.05,
        8.49, 10.56, 12.46,  7.52,  7.63, 14.76,  6.24,  3.95, 11.7 ,
       10.5 ,  3.73,  8.81,  3.66,  1.91,  9.54,  6.82,  9.88,  9.99,
        8.43,  9.38, 13.24,  7.91,  9.69,  3.83,  9.6 , 14.4 ,  3.07,
        4.45,  8.7 , 14.4 , 13.8 ,  7.72, 10.57,  8.94,  7.9 ,  7.79,
        3.8 ,  9.25,  6.33, 13.58,  8.46,  5.57,  6.6 , 12.39,  4.86,
        5.92,  8.11, 11.68,  8.73, 11.97,  7.75,  8.67,  9.23, 12.88,
       10.18,  8.65,  8.91,  3.72,  2.73,  4.54, 10.17,  9.59, 10.61,
        9.62,  7.56, 14.2 ,  8.19,  4.84, 10.13,  1.76,  8.69,  2.65,
        8.97,  6.81,  4.56, 10.62, 10.88,  6.41,  6.99,  7.83, 12.52,
        9.09, 11.63,  8.26,  8.53,  8.57,  6.3 , 11.87,  3.34,  8.91,
        7.77,  3.34,

In [95]:
np.argmax(price_range)

np.int64(325)

In [96]:
np.argmin(price_range)

np.int64(200)

In [97]:
print('Average Trading Value', np.mean(volume))

Average Trading Value 2643580.81


In [98]:
print('Maximum Volumne', np.max(volume))

Maximum Volumne 4999214.0


In [99]:
print('Day having maximum trade volume', arr[np.argmax(volume)])

Day having maximum trade volume [    213.8      215.96     212.21     213.19 4999214.  ]


## Indexes and Slicing

In [104]:
arr[arr[:,3]>170][:10,:]

array([[    167.23,     173.76,     163.99,     171.71,  216758.  ],
       [    170.3 ,     171.73,     167.04,     170.55, 2299169.  ],
       [    167.17,     173.57,     165.13,     172.13, 4749031.  ],
       [    168.08,     173.05,     165.5 ,     172.93, 1190453.  ],
       [    173.17,     179.66,     171.85,     178.62, 1205645.  ],
       [    175.71,     182.13,     173.43,     176.25, 1561683.  ],
       [    174.84,     176.29,     171.18,     171.76,  633163.  ],
       [    166.77,     171.88,     160.82,     170.87, 4474249.  ],
       [    169.68,     175.01,     168.95,     175.  , 3469009.  ],
       [    174.56,     175.87,     168.72,     171.89,  777719.  ]])

In [106]:
arr[arr[:,4]>3000000][:10,:]

array([[    150.  ,     152.24,     144.98,     149.05, 4671300.  ],
       [    154.15,     160.12,     149.63,     159.84, 3275376.  ],
       [    157.31,     160.01,     152.1 ,     159.1 , 3133614.  ],
       [    163.14,     170.05,     156.14,     161.43, 3903481.  ],
       [    161.54,     167.17,     160.5 ,     164.74, 4580690.  ],
       [    166.11,     167.84,     162.76,     167.79, 4772033.  ],
       [    162.19,     165.7 ,     161.19,     165.31, 4857851.  ],
       [    167.57,     170.43,     162.15,     165.43, 3949128.  ],
       [    163.29,     164.84,     157.2 ,     161.32, 3693963.  ],
       [    163.71,     167.21,     161.57,     167.2 , 4374216.  ]])

In [109]:
arr[(arr[:,3]>170)&(arr[:,4]>3000000)][:10,:]

array([[    167.17,     173.57,     165.13,     172.13, 4749031.  ],
       [    166.77,     171.88,     160.82,     170.87, 4474249.  ],
       [    169.68,     175.01,     168.95,     175.  , 3469009.  ],
       [    170.82,     172.43,     169.37,     171.28, 4699947.  ],
       [    172.55,     175.91,     167.57,     170.03, 4340869.  ],
       [    170.66,     171.9 ,     164.9 ,     170.87, 4724935.  ],
       [    173.35,     176.93,     166.3 ,     176.3 , 3647851.  ],
       [    178.51,     184.42,     170.75,     178.96, 3049822.  ],
       [    179.06,     185.9 ,     171.25,     183.24, 4770271.  ],
       [    168.69,     174.99,     164.48,     172.41, 4960930.  ]])

In [137]:
close_price.argsort()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 140, 139, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [142]:
arr[:489:-1]

array([[    175.96,     182.95,     168.32,     222.6 , 1736856.  ],
       [    174.99,     179.16,     173.44,     222.24, 3883270.  ],
       [    171.21,     175.36,     166.68,     221.3 , 1553198.  ],
       [    174.21,     178.54,     170.57,     220.91, 3318792.  ],
       [    174.74,     177.59,     172.45,     220.41, 3231518.  ],
       [    175.81,     182.41,     170.02,     220.  ,  810951.  ],
       [    176.54,     181.62,     171.64,     219.78, 3940812.  ],
       [    177.95,     180.42,     170.98,     219.21, 2729024.  ],
       [    178.7 ,     185.2 ,     174.17,     218.51, 1753178.  ],
       [    174.39,     180.18,     172.35,     218.38,  624822.  ]])

#### These are top 10 highest closing price days.

In [144]:
volume.argsort()

array([154, 441, 195, 435, 284,  96, 185,  65, 352,   1, 330, 233, 106,
        33, 440,  13, 374, 475, 169, 373, 146,  62, 113, 443, 477, 425,
       432, 406, 186, 340, 134, 239, 323, 177, 407,  42, 431, 332, 396,
       390, 357, 490, 213, 223, 405,  47,  69, 141,  51, 418,  84, 314,
       254, 250, 450, 255, 447, 243, 449, 416, 217, 236, 454, 494, 235,
       476, 482, 372, 458,  82, 345,  40,  37, 202, 176, 129,   0, 151,
        86, 228, 355,  21,  60, 311, 159, 109,  20, 200, 312, 384,  31,
       157,  76, 278, 107, 131, 241, 210, 211, 393, 377,  55, 162, 188,
       347, 283, 143, 307, 288, 333, 346, 414, 279, 209, 249, 437, 263,
       433,  94, 309, 171, 403, 234, 370,   3,  18,  24, 276, 378, 391,
        81, 327, 497, 212, 294, 231, 302, 271, 232, 295, 381, 289, 166,
       205,  73, 417, 298,  38, 343, 499, 491, 142, 111,  83, 371, 356,
       446, 138, 103,  29, 420, 206,  34, 388,  99,  32, 386, 198, 401,
       361, 324, 136, 439, 229, 268, 175,  68, 147, 187, 197, 30

In [152]:
arr[volume.argsort()][::-1][:10]


array([[    213.8 ,     215.96,     212.21,     200.3 , 4999214.  ],
       [    208.95,     213.35,     207.58,     194.62, 4991797.  ],
       [    179.27,     182.36,     173.27,     176.92, 4981358.  ],
       [    129.62,     130.33,     122.54,     132.4 , 4970339.  ],
       [    129.31,     129.83,     123.36,     158.9 , 4964749.  ],
       [    168.69,     174.99,     164.48,     171.87, 4960930.  ],
       [    196.97,     199.46,     191.55,     188.97, 4952594.  ],
       [    208.22,     211.69,     201.6 ,     194.82, 4951226.  ],
       [    187.4 ,     194.38,     186.29,     183.24, 4938307.  ],
       [    183.55,     191.5 ,     181.29,     197.65, 4932763.  ]])

#### These are top 10 highest volume days.